/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.nabavke.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import sistem.nabavke.controler.Controler;

/**
 *
 * @author skiljevic
 */
public class GuiMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMainMenu
     */
    public GuiMainMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
			Controler.zatvoriGlavniMenu();
			}
		});
//        this.setDefaultCloseOperation(Controler.zatvoriGlavniMenu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDobavljac = new javax.swing.JMenu();
        menuItemKreirajDobavljaca = new javax.swing.JMenuItem();
        menuItemPregledDobavljaca = new javax.swing.JMenuItem();
        menuNarudzbenica = new javax.swing.JMenu();
        menuItemKreirajNarudzbenicu = new javax.swing.JMenuItem();
        menuItemPrgledNarudzbenice = new javax.swing.JMenuItem();
        menuDodajKorisnika = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem nabavke");

        jLabel1.setText("Ulogovani korisnik:");

        lblAdmin.setForeground(new java.awt.Color(255, 102, 102));

        menuDobavljac.setText("Dobavljac");

        menuItemKreirajDobavljaca.setText("Kreiraj");
        menuItemKreirajDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajDobavljacaActionPerformed(evt);
            }
        });
        menuDobavljac.add(menuItemKreirajDobavljaca);

        menuItemPregledDobavljaca.setText("Pretraga");
        menuItemPregledDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPregledDobavljacaActionPerformed(evt);
            }
        });
        menuDobavljac.add(menuItemPregledDobavljaca);

        jMenuBar1.add(menuDobavljac);

        menuNarudzbenica.setText("Narudzbenica");

        menuItemKreirajNarudzbenicu.setText("Kreiraj");
        menuItemKreirajNarudzbenicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajNarudzbenicuActionPerformed(evt);
            }
        });
        menuNarudzbenica.add(menuItemKreirajNarudzbenicu);

        menuItemPrgledNarudzbenice.setText("Pretraga");
        menuItemPrgledNarudzbenice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrgledNarudzbeniceActionPerformed(evt);
            }
        });
        menuNarudzbenica.add(menuItemPrgledNarudzbenice);

        jMenuBar1.add(menuNarudzbenica);

        menuDodajKorisnika.setText("Dodaj korisnika");
        menuDodajKorisnika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDodajKorisnikaMouseClicked(evt);
            }
        });
        menuDodajKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDodajKorisnikaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuDodajKorisnika);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsername)
                    .addComponent(lblAdmin))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDodajKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDodajKorisnikaActionPerformed

    }//GEN-LAST:event_menuDodajKorisnikaActionPerformed

    private void menuDodajKorisnikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDodajKorisnikaMouseClicked
        Controler.dodajKorisnikaButtonPressed();
    }//GEN-LAST:event_menuDodajKorisnikaMouseClicked

    private void menuItemKreirajDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajDobavljacaActionPerformed
        Controler.otvoriProzorKreiranjeDobavljaca();
    }//GEN-LAST:event_menuItemKreirajDobavljacaActionPerformed

    private void menuItemKreirajNarudzbenicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajNarudzbenicuActionPerformed
        Controler.otvoriProzorKreiranjeNarudzbenice();
    }//GEN-LAST:event_menuItemKreirajNarudzbenicuActionPerformed

    private void menuItemPregledDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPregledDobavljacaActionPerformed
        Controler.otvoriPretragaDobacljaca();
    }//GEN-LAST:event_menuItemPregledDobavljacaActionPerformed

    private void menuItemPrgledNarudzbeniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrgledNarudzbeniceActionPerformed
        Controler.otvoriProzorPretragaNarudzbenice();
    }//GEN-LAST:event_menuItemPrgledNarudzbeniceActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu menuDobavljac;
    private javax.swing.JMenu menuDodajKorisnika;
    private javax.swing.JMenuItem menuItemKreirajDobavljaca;
    private javax.swing.JMenuItem menuItemKreirajNarudzbenicu;
    private javax.swing.JMenuItem menuItemPregledDobavljaca;
    private javax.swing.JMenuItem menuItemPrgledNarudzbenice;
    private javax.swing.JMenu menuNarudzbenica;
    // End of variables declaration//GEN-END:variables

    public String getLblUsername() {
        return lblUsername.getText();
    }

    public void setLblUsername(String lblUsername) {
        this.lblUsername.setText(lblUsername);
    }

    public String getLblAdmin() {
        return lblAdmin.getText();
    }

    public void setLblAdmin(String lblAdmin) {
        this.lblAdmin.setText(lblAdmin);
    }

    public void hideMainMenu() {
        this.menuDodajKorisnika.setVisible(false);
    }
    
    
    
}
