/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.nabavke.gui.dobavljac;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import sistem.nabavke.controler.Controler;
import sistem.nabavke.logic.Logika;

/**
 *
 * @author skiljevic
 */
public class GuiDobavljacKreiranje extends javax.swing.JDialog {

    /**
     * Creates new form GuiDobavljacKreiranje
     */
    public GuiDobavljacKreiranje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Controler.zatvoriProzorKreiranjeDobavljaca();
            }
        });
        this.btnAzurirajDobavljaca.setVisible(false);
        this.btnKreirajDobavljaca.setVisible(true);
        this.setTitle("Kreiranje dobavljaca");
    }

    public GuiDobavljacKreiranje(String pib, String naziv, String adresa, java.awt.Frame parent, boolean modal) {
        this(parent, modal);
        this.btnKreirajDobavljaca.setVisible(false);
        this.btnAzurirajDobavljaca.setVisible(true);
        this.setTitle("Azuriranje dobavljaca");
        this.txtPib.setText(pib);
        this.txtNaziv.setText(naziv);
        this.txtAdresa.setText(adresa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPib = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        btnKreirajDobavljaca = new javax.swing.JButton();
        btnAzurirajDobavljaca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiranje dobavljaca");

        jLabel1.setText("Pib:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Adresa");

        txtPib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPibActionPerformed(evt);
            }
        });

        btnKreirajDobavljaca.setText("Kreiraj");
        btnKreirajDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajDobavljacaActionPerformed(evt);
            }
        });

        btnAzurirajDobavljaca.setText("Azuriraj");
        btnAzurirajDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajDobavljacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(txtNaziv)
                    .addComponent(txtPib))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAzurirajDobavljaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKreirajDobavljaca, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnKreirajDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAzurirajDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPibActionPerformed

    private void btnKreirajDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajDobavljacaActionPerformed

        Controler.kreirajDobavljacaButtonPressed(txtAdresa.getText(), txtPib.getText(), txtNaziv.getText());
    }//GEN-LAST:event_btnKreirajDobavljacaActionPerformed

    private void btnAzurirajDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajDobavljacaActionPerformed
        Controler.azurirajDobavljacaButtonPressed(txtPib.getText(), txtNaziv.getText(), txtAdresa.getText());
    }//GEN-LAST:event_btnAzurirajDobavljacaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzurirajDobavljaca;
    private javax.swing.JButton btnKreirajDobavljaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPib;
    // End of variables declaration//GEN-END:variables
}
